//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem_A
    {
        public int Id { get; set; }
        public string ProId { get; set; }
        public Nullable<System.DateTime> OccurredTime { get; set; }
        public Nullable<int> Week { get; set; }
        public string ComplaintsType { get; set; }
        public string Customer { get; set; }
        public string Model { get; set; }
        public string CusPartNum { get; set; }
        public string InPartNum { get; set; }
        public string Factory { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> DefectNum { get; set; }
        public string SpecialEffects { get; set; }
        public string RiskLevel { get; set; }
        public string RiskAssessment { get; set; }
        public string DefectLevel { get; set; }
        public string DescribePro { get; set; }
        public string Reason { get; set; }
        public string Measure { get; set; }
        public string Responsible_Department { get; set; }
        public string Responsible_Person { get; set; }
        public Nullable<System.DateTime> ReportTime { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<bool> PastDue { get; set; }
    }
}
